#!/usr/bin/env bash

set -eu

SUNSHINE_JAR=$1
if [ ! -f "$SUNSHINE_JAR" ]; then
    echo "FAILURE: Cannot find file $SUNSHINE"
    exit 1
fi
readonly SUNSHINE="java -jar ${SUNSHINE_JAR}"

LANG_DIR=$2
if [ ! -d "$LANG_DIR" ]; then
    echo "FAILURE: Cannot find directory $LANG_DIR"
    exit 1
fi

shift 2

for infile in "$@"
do
    stxoutfile=${infile%.*}.stx.out

    if ! (echo $infile | grep -s ".no." >&/dev/null)
    then
        positive=0
	    #echo "Expect pass"
    else
        positive=1
	    #echo "Expect fail"
    fi

    # run statix on the aterm
    statix check -I src/ lmr ${infile} 2>&1 >${stxoutfile} && stx_ok=0 || stx_ok=1

    # compute test result by comparison
    if [ $stx_ok -eq $positive ]
    then
        echo -e "[\e[32mSUCCESS\e[0m] $infile"
    else
        echo -e "[\e[31mFAILURE\e[0m] $infile (see $stxoutfile)"
    fi
done
