[
   TXInt               -- KW["Int"],
   TXBool              -- KW["Bool"],
   TXArrow             -- _1 KW["->"] _2,
   TXRec               -- _1,
   TInt                -- KW["Int"],
   TBool               -- KW["Bool"],
   TArrow              -- _1 KW["->"] _2,
   TRec                -- _1,
   This                -- KW["this"],
   COMPLETION-Type     -- _1,
   COMPLETION-TypeS    -- _1,
   COMPLETION-Types    -- _1,
   COMPLETION-This     -- _1,
   Int                 -- _1,
   True                -- KW["true"],
   False               -- KW["false"],
   Add                 -- _1 KW["+"] _2,
   Sub                 -- _1 KW["-"] _2,
   Mul                 -- _1 KW["*"] _2,
   Div                 -- _1 KW["/"] _2,
   And                 -- _1 KW["&"] _2,
   Or                  -- _1 KW["|"] _2,
   Eq                  -- _1 KW["=="] _2,
   App                 -- _1 _2,
   If                  -- KW["if"] _1 KW["then"] _2 KW["else"] _3,
   Fun                 -- KW["fun"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   ArgDecl             -- _1 KW[":"] _2,
   Let                 -- KW["let"] _1 KW["in"] _2,
   Let.1:iter          -- _1,
   LetRec              -- KW["letrec"] _1 KW["in"] _2,
   LetRec.1:iter       -- _1,
   LetPar              -- KW["letpar"] _1 KW["in"] _2,
   LetPar.1:iter       -- _1,
   DefBind             -- _1 KW["="] _2,
   DefBindTyped        -- _1 KW[":"] _2 KW["="] _3,
   COMPLETION-ArgDecl  -- _1,
   COMPLETION-Expr     -- _1,
   COMPLETION-DefBind  -- _1,
   Rec                 -- KW["record"] _1 _2 KW["{"] _3 KW["}"],
   Rec.3:iter-star-sep -- _1 KW[","],
   NoSuper             -- ,
   Super               -- KW["extends"] _1,
   New                 -- KW["new"] _1 KW["{"] _2 KW["}"],
   New.2:iter-star-sep -- _1 KW[","],
   FldBind             -- _1 KW["="] _2,
   FldAccess           -- _1 KW["."] _2,
   With                -- KW["with"] _1 KW["do"] _2,
   COMPLETION-Decl     -- _1,
   COMPLETION-Super    -- _1,
   COMPLETION-FldBind  -- _1,
   COMPLETION-Expr     -- _1,
   ModRef              -- _1,
   ModQRef             -- _1 KW["."] _2,
   TypeRef             -- _1,
   TypeQRef            -- _1 KW["."] _2,
   VarRef              -- _1,
   VarQRef             -- _1 KW["."] _2,
   COMPLETION-ModId    -- _1,
   COMPLETION-ModRef   -- _1,
   COMPLETION-TypeId   -- _1,
   COMPLETION-TypeRef  -- _1,
   COMPLETION-VarId    -- _1,
   COMPLETION-VarRef   -- _1,
   Program             -- KW["program"] _1 _2,
   Program.2:iter-star -- _1,
   Module              -- KW["module"] _1 KW["{"] _2 KW["}"],
   Module.2:iter-star  -- _1,
   Import              -- KW["import"] _1,
   Def                 -- KW["def"] _1,
   COMPLETION-Program  -- _1,
   COMPLETION-Decl     -- _1
]