[
   DeclId                 -- KW["decl"] KW["("] _1 KW[","] _2 KW[","] _3 KW[")"],
   RefId                  -- KW["ref"] KW["("] _1 KW[","] _2 KW[","] _3 KW[")"],
   QNil                   -- ,
   QRef                   -- _1 KW["."] _2,
   ModNs                  -- KW["mod"],
   VarNs                  -- KW["var"],
   TypeNs                 -- KW["type"],
   U                      -- ,
   COMPLETION-DeclId      -- _1,
   COMPLETION-RefId       -- _1,
   COMPLETION-QualRef     -- _1,
   COMPLETION-Ns          -- _1,
   COMPLETION-U           -- _1,
   Program                -- KW["program"] _1 _2,
   Program.2:iter-star    -- _1,
   Module                 -- KW["module"] _1 KW["{"] _2 KW["}"],
   Module.2:iter-star     -- _1,
   Import                 -- KW["import"] _1,
   Def                    -- KW["def"] _1,
   Rec                    -- KW["record"] _1 _2 KW["{"] _3 KW["}"],
   Rec.3:iter-star-sep    -- _1 KW[","],
   NoSuper                -- ,
   Super                  -- KW["extends"] _1,
   COMPLETION-Program     -- _1,
   COMPLETION-Stmt        -- _1,
   COMPLETION-Super       -- _1,
   Int                    -- _1,
   True                   -- KW["true"],
   False                  -- KW["false"],
   Add                    -- _1 KW["+"] _2,
   Sub                    -- _1 KW["-"] _2,
   Mul                    -- _1 KW["*"] _2,
   Div                    -- _1 KW["/"] _2,
   And                    -- _1 KW["&"] _2,
   Or                     -- _1 KW["|"] _2,
   Eq                     -- _1 KW["=="] _2,
   If                     -- KW["if"] _1 KW["then"] _2 KW["else"] _3,
   Ref                    -- _1,
   App                    -- _1 _2,
   Fun                    -- KW["fun"] KW["("] _1 KW[")"] KW["{"] _2 KW["}"],
   Let                    -- KW["let"] _1 KW["in"] _2,
   Let.1:iter             -- _1,
   LetRec                 -- KW["letrec"] _1 KW["in"] _2,
   LetRec.1:iter          -- _1,
   LetPar                 -- KW["letpar"] _1 KW["in"] _2,
   LetPar.1:iter          -- _1,
   New                    -- KW["new"] _1 KW["{"] _2 KW["}"],
   New.2:iter-star-sep    -- _1 KW[","],
   FldBind                -- _1 KW["="] _2,
   FldAccess              -- _1 KW["."] _2,
   With                   -- KW["with"] _1 KW["do"] _2,
   DefBind                -- _1 KW["="] _2,
   ArgDecl                -- _1 KW[":"] _2,
   TypedDefDecl           -- _1 KW[":"] _2,
   DefDecl                -- _1,
   COMPLETION-FldBind     -- _1,
   COMPLETION-Expr        -- _1,
   COMPLETION-DefBind     -- _1,
   COMPLETION-ArgDecl     -- _1,
   COMPLETION-DefDecl     -- _1,
   ModDeclId              -- _1,
   ModRefId               -- _1,
   ModUnqualRef           -- _1,
   ModQualRef             -- _1 KW["."] _2,
   TypeDeclId             -- _1,
   TypeRefId              -- _1,
   TypeUnqualRef          -- _1,
   TypeQualRef            -- _1 KW["."] _2,
   VarDeclId              -- _1,
   VarRefId               -- _1,
   VarUnqualRef           -- _1,
   VarQualRef             -- _1 KW["."] _2,
   COMPLETION-ModDeclId   -- _1,
   COMPLETION-ModRefId    -- _1,
   COMPLETION-ModQualRef  -- _1,
   COMPLETION-TypeDeclId  -- _1,
   COMPLETION-TypeRefId   -- _1,
   COMPLETION-TypeQualRef -- _1,
   COMPLETION-VarDeclId   -- _1,
   COMPLETION-VarRefId    -- _1,
   COMPLETION-VarQualRef  -- _1,
   TXInt                  -- KW["Int"],
   TXBool                 -- KW["Bool"],
   TXArrow                -- _1 KW["->"] _2,
   TXRec                  -- _1,
   COMPLETION-TypeX       -- _1
]